[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.26"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "paris"

[rpc_endpoints]
armoy = "${AMOY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
armoy = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }