[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.30"
optimizer = true
optimizer_runs = 1000000
via_ir = true
evm_version = "paris"

# Additional optimizations to help with stack overflow
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[rpc_endpoints]
armoy = "${AMOY_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
armoy = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }